service:
  name: datalake-analytics-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  deploymentBucket: ${self:service.name}-deploy
  memorySize: 128
  timeout: 180
  vpc:
    securityGroupIds:
      - sg-066d9216f85924c46
    subnetIds:
      - subnet-0d770250
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:PutMetricData"
      Resource:
        - "*"

package:
  exclude:
    - "**/**"
  individually: true

functions:
  product:
    name: datalake-analytics-api-${self:provider.stage}-store
    handler: analytics/store-analytics.handler
    package:
      include:
        - ../analytics/store-analytics.js
        - node_modules/**
